// react/homework/src/components/User Component.js
import React, {Component} from 'react';
import './User.css'

class UserComponent extends Component {
    render() {
        let {item} = this.props;
        console.log(this.props);
        return (
            <div className='user'>
                {item.name}-{item.age}-{item.status.toString()}
            </div>
        );
    }
}

export default UserComponent;

// angular/angular-practise/src/app/user/user.component.ts
import {Component, Input, OnInit} from '@angular/core';

@Component({
  selector: 'app-user',
  templateUrl: './user.component.html',
  styleUrls: ['./user.component.css']
})
export class UserComponent implements OnInit {
  @Input()
  user: any;

  constructor() { }

  ngOnInit(): void {
  }
}

<div>
  Name: {{user.name}}
  <br/>
  Age: {{user.age}}
  <br/>
  Status: {{user.status}}
  <br/>
  <app-address [address]="user.address"></app-address>
</div>
